#
# Refer to the end of this file to have a look at a sample format of the
# log file that this job is meant to process.
#

# The version of this job configuration file. This should not be changed by the user.
version: 2

# Optional property. Defaults to "false"
#
enabled: false

# Mandatory property.
#
# Source can be of two types:
#   1) file: This allows tailing a log file. It consists of three parameters:
#       - path: Path to the directory where files need to be tailed.
#       - nameGlob: The name/expression to tail the matching files.
#       - startAtEnd: If set to true allows tailing the file from the end.
#         Example:
#         1) path: /var/log
#            nameGlob: */*.log searches for .log files one level deep in the /var/log
#            directory (matches '/var/log/cassandra/system.log' but not
#            '/var/log/apache2/logs/error.log').
#         2) path: /var/log
#            nameGlob: **/*.log searches for .log files even in the sub-directories in
#            /var/log directory (matches both '/var/log/apache2/logs/error.log' and
#            '/var/log/cassandra/system.log').
#       On Windows, path should be provided as if on Unix environments.
#       Ex: demo/logs
#       Ex: C:/app/logs
#   2) syslog: Listens to Syslog messages on a network port. It consists of two parameters:
#       - protocol: The transport layer protocol that will be used. Currently
#         we support only tcp.
#       - port: The port at which the server will be listening to receive the
#         syslog messages. Currently, we support one port per job file, and any
#         enabled job file should be configured to receive messages at different
#         ports. The user must make sure it does not conflict with anything else
#         active in network. If no port number is provided, default port 514
#         will be used.
#
source:
    type: file
    path: /opt/jetty-distribution-9.2.3.v20140905/demo-base/logs
    nameGlob: "*.stderrout.log"
    startAtEnd: false

#
# Optional property (Except "sourceType").
#
# These fields are in addition to the data that is already present in the
# files being tailed. Each record read from the file will be enriched with
# these fields.
#
fields:
   sourceType: jetty-error-log
   nodeName: Node1
   tierName: Tier1
   appName: App1

# Optional property.
#
# Grok is a way to define and use complex, nested regular expressions in an
# easy to read and use format.
#
# A Grok pattern ultimately resolves and compiles into a regular expression.
# The advantage of using Grok is its ability to compose complex patterns from
# simpler pattern definitions, like a "formal grammar".
#
# See https://grokdebug.herokuapp.com/patterns for examples.
#
# The application comes pre-loaded with some well known Grok patterns in
# the form of ".grok" files. They are available under the "conf/grok" directory.
# Custom Grok files can be added to this directory and they will be
# available for use here when the application is restarted.
#
# The Grok patterns here are meant to match a part of the log "message" string.
# If multiple Grok patterns are provided, each one will be applied to the
# "message" string individually.
#
# A Grok pattern is really a regular expression with the option of referencing
# other known Grok patterns by name. Like this "%{JAVACLASS:myClassName}".
# This means that we are looking for a sub-string that looks like a Java Class
# name. Once the pattern is found, the matching sub-string will be extracted
# and stored separately as a first class field, with "myClassName" as the key.
#
# By default, these patterns do not match multiline strings. To look for
# the pattern sub-string across a multiline string, please refer to:
# http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#DOTALL
#
grok:
  patterns:
    - "%{JETTY_ERROR_TIMESTAMP:eventTimestamp}:%{LOGLEVEL:logLevel}:%{JAVACLASS:class}:%{DATA:threadName}: %{GREEDYDATA}"

# Optional property.
#
# The KeyValue Stage is a way to support parsing of logs to identify and capture
# key-value pairs with a user defined delimiter.
# The KeyValue Stage is defined after the Grok Stage (if defined), and can leverage
# parsing done in the GrokStage to identify the key-value pairs in the logs.
# For details refer to 'sample-glassfish-log.job' file.

# Optional property.
#
# RequestGuid attempts to extract the request GUID from the specified "source" field.
# For details refer to 'sample-analytics-log-with-request-guid.job' file.

# Optional property.
#
# If records have a timestamp that should be used as "the" eventTimestamp then
# the format can be provided here to ensure that the string gets parsed and
# transformed correctly to UTC time zone.
#
# An attempt will be made to extract the timestamp automatically, failing which
# one will be added at the time the record is read from the file.
#
# UTC time zone is used throughout the system to ensure consistency of
# timestamps across sources from different time zones. This means that all
# timestamps should be converted to UTC time zone.
#
# If the format ends with a "z" or "Z" then the time zone offset is used to
# convert to UTC time. No time zone means local time zone.
#
# A reference list of available patterns can be found here:
# http://www.joda.org/joda-time/key_format.html
#
eventTimestamp:
   pattern: "yyyy-MM-dd HH:mm:ss"

# Optional property.
#
# The transform stage is applied after all fields have been captured from the log message.
# The user can specify a list of field names, for which they want to cast
# the value to a specific type or rename the field with an "alias".
# For details refer to 'sample-glassfish-log.job' file.

# ####################################
# ###   Start sample file format   ###
# ####################################
#
# 2015-01-14 15:16:12.744:WARN::main: demo test-realm is deployed. DO NOT USE IN PRODUCTION!
# 2015-01-14 15:16:12.766:INFO:oejs.Server:main: jetty-9.2.3.v20140905
# 2015-01-14 15:16:12.782:INFO:oejs.AbstractNCSARequestLog:main: Opened /opt/jetty-distribution-9.2.3.v20140905/demo-base/ logs/2015_01_14.request.log
# 2015-01-14 15:16:12.786:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:/opt/jetty-distribution-9.2.3.v20140905/demo-base/webapps/] at interval 1
# 2015-01-14 15:16:14.183:WARN::main: test webapp is deployed. DO NOT USE IN PRODUCTION!
# 2015-01-14 15:16:14.860:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@6f32971a{/test,file:/tmp/jetty-0.0.0.0-8080-test.war-_test-any-4884054485148281107.dir/webapp/,AVAILABLE}{/test.war}
# 2015-01-14 15:16:15.065:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@552864df{/,file:/opt/jetty-distribution-9.2.3.v20140905/demo-base/webapps/ROOT/,AVAILABLE}{/ROOT}
# 2015-01-14 15:16:15.078:INFO:oejsh.ContextHandler:main: Started o.e.j.s.h.MovedContextHandler@3795473d{/oldContextPath,null,AVAILABLE}
# 2015-01-14 15:16:15.449:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@2978124d{/proxy,file:/tmp/jetty-0.0.0.0-8080-xref-proxy.war-_xref-proxy-any-3734765081346973704.dir/webapp/,AVAILABLE}{/xref-proxy.war}
# 2015-01-14 15:16:15.573:WARN::main: test-jaas webapp is deployed. DO NOT USE IN PRODUCTION!
#
# ##################################
# ###   End sample file format   ###
# ##################################
